// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: oneof/hello.proto

package oneof

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Name:
	//
	//	*HelloRequest_FirstName
	//	*HelloRequest_LastName
	Name isHelloRequest_Name `protobuf_oneof:"name"`
	// Types that are assignable to Gender:
	//
	//	*HelloRequest_Male
	//	*HelloRequest_Female
	Gender isHelloRequest_Gender `protobuf_oneof:"gender"`
	// Types that are assignable to DefaultValues:
	//
	//	*HelloRequest_DefaultInt
	//	*HelloRequest_DefaultString
	DefaultValues isHelloRequest_DefaultValues `protobuf_oneof:"default_values"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneof_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_oneof_hello_proto_rawDescGZIP(), []int{0}
}

func (m *HelloRequest) GetName() isHelloRequest_Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (x *HelloRequest) GetFirstName() string {
	if x, ok := x.GetName().(*HelloRequest_FirstName); ok {
		return x.FirstName
	}
	return ""
}

func (x *HelloRequest) GetLastName() string {
	if x, ok := x.GetName().(*HelloRequest_LastName); ok {
		return x.LastName
	}
	return ""
}

func (m *HelloRequest) GetGender() isHelloRequest_Gender {
	if m != nil {
		return m.Gender
	}
	return nil
}

func (x *HelloRequest) GetMale() bool {
	if x, ok := x.GetGender().(*HelloRequest_Male); ok {
		return x.Male
	}
	return false
}

func (x *HelloRequest) GetFemale() bool {
	if x, ok := x.GetGender().(*HelloRequest_Female); ok {
		return x.Female
	}
	return false
}

func (m *HelloRequest) GetDefaultValues() isHelloRequest_DefaultValues {
	if m != nil {
		return m.DefaultValues
	}
	return nil
}

func (x *HelloRequest) GetDefaultInt() int32 {
	if x, ok := x.GetDefaultValues().(*HelloRequest_DefaultInt); ok {
		return x.DefaultInt
	}
	return 0
}

func (x *HelloRequest) GetDefaultString() string {
	if x, ok := x.GetDefaultValues().(*HelloRequest_DefaultString); ok {
		return x.DefaultString
	}
	return ""
}

type isHelloRequest_Name interface {
	isHelloRequest_Name()
}

type HelloRequest_FirstName struct {
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3,oneof"`
}

type HelloRequest_LastName struct {
	LastName string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof"`
}

func (*HelloRequest_FirstName) isHelloRequest_Name() {}

func (*HelloRequest_LastName) isHelloRequest_Name() {}

type isHelloRequest_Gender interface {
	isHelloRequest_Gender()
}

type HelloRequest_Male struct {
	Male bool `protobuf:"varint,3,opt,name=male,proto3,oneof"`
}

type HelloRequest_Female struct {
	Female bool `protobuf:"varint,4,opt,name=female,proto3,oneof"`
}

func (*HelloRequest_Male) isHelloRequest_Gender() {}

func (*HelloRequest_Female) isHelloRequest_Gender() {}

type isHelloRequest_DefaultValues interface {
	isHelloRequest_DefaultValues()
}

type HelloRequest_DefaultInt struct {
	DefaultInt int32 `protobuf:"varint,5,opt,name=default_int,json=defaultInt,proto3,oneof"`
}

type HelloRequest_DefaultString struct {
	DefaultString string `protobuf:"bytes,6,opt,name=default_string,json=defaultString,proto3,oneof"`
}

func (*HelloRequest_DefaultInt) isHelloRequest_DefaultValues() {}

func (*HelloRequest_DefaultString) isHelloRequest_DefaultValues() {}

// The response message containing the greetings
type HelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneof_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_oneof_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_oneof_hello_proto protoreflect.FileDescriptor

var file_oneof_hello_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0xee, 0x01, 0x0a, 0x0c, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x09,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x6d,
	0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x04, 0x6d, 0x61, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x06, 0x66, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x01, 0x52, 0x06, 0x66, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x02, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x74, 0x12, 0x27,
	0x0a, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x06, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42,
	0x08, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x10, 0x0a, 0x0e, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x47, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x12, 0x13, 0x2e, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x30,
	0x34, 0x39, 0x32, 0x32, 0x31, 0x30, 0x31, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oneof_hello_proto_rawDescOnce sync.Once
	file_oneof_hello_proto_rawDescData = file_oneof_hello_proto_rawDesc
)

func file_oneof_hello_proto_rawDescGZIP() []byte {
	file_oneof_hello_proto_rawDescOnce.Do(func() {
		file_oneof_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_oneof_hello_proto_rawDescData)
	})
	return file_oneof_hello_proto_rawDescData
}

var file_oneof_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oneof_hello_proto_goTypes = []interface{}{
	(*HelloRequest)(nil),  // 0: oneof.HelloRequest
	(*HelloResponse)(nil), // 1: oneof.HelloResponse
}
var file_oneof_hello_proto_depIdxs = []int32{
	0, // 0: oneof.HelloService.SayHello:input_type -> oneof.HelloRequest
	1, // 1: oneof.HelloService.SayHello:output_type -> oneof.HelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oneof_hello_proto_init() }
func file_oneof_hello_proto_init() {
	if File_oneof_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oneof_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneof_hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_oneof_hello_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*HelloRequest_FirstName)(nil),
		(*HelloRequest_LastName)(nil),
		(*HelloRequest_Male)(nil),
		(*HelloRequest_Female)(nil),
		(*HelloRequest_DefaultInt)(nil),
		(*HelloRequest_DefaultString)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oneof_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oneof_hello_proto_goTypes,
		DependencyIndexes: file_oneof_hello_proto_depIdxs,
		MessageInfos:      file_oneof_hello_proto_msgTypes,
	}.Build()
	File_oneof_hello_proto = out.File
	file_oneof_hello_proto_rawDesc = nil
	file_oneof_hello_proto_goTypes = nil
	file_oneof_hello_proto_depIdxs = nil
}
