// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: updatefield/old/old.proto

package old

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest_Sport int32

const (
	HelloRequest_SPORT_UNKNOWN    HelloRequest_Sport = 0
	HelloRequest_SPORT_BASEBALL   HelloRequest_Sport = 1
	HelloRequest_SPORT_BASKETBALL HelloRequest_Sport = 2
)

// Enum value maps for HelloRequest_Sport.
var (
	HelloRequest_Sport_name = map[int32]string{
		0: "SPORT_UNKNOWN",
		1: "SPORT_BASEBALL",
		2: "SPORT_BASKETBALL",
	}
	HelloRequest_Sport_value = map[string]int32{
		"SPORT_UNKNOWN":    0,
		"SPORT_BASEBALL":   1,
		"SPORT_BASKETBALL": 2,
	}
)

func (x HelloRequest_Sport) Enum() *HelloRequest_Sport {
	p := new(HelloRequest_Sport)
	*p = x
	return p
}

func (x HelloRequest_Sport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HelloRequest_Sport) Descriptor() protoreflect.EnumDescriptor {
	return file_updatefield_old_old_proto_enumTypes[0].Descriptor()
}

func (HelloRequest_Sport) Type() protoreflect.EnumType {
	return &file_updatefield_old_old_proto_enumTypes[0]
}

func (x HelloRequest_Sport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HelloRequest_Sport.Descriptor instead.
func (HelloRequest_Sport) EnumDescriptor() ([]byte, []int) {
	return file_updatefield_old_old_proto_rawDescGZIP(), []int{0, 0}
}

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number int32              `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Sport  HelloRequest_Sport `protobuf:"varint,3,opt,name=sport,proto3,enum=unary.HelloRequest_Sport" json:"sport,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updatefield_old_old_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_updatefield_old_old_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_updatefield_old_old_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *HelloRequest) GetSport() HelloRequest_Sport {
	if x != nil {
		return x.Sport
	}
	return HelloRequest_SPORT_UNKNOWN
}

// The response message containing the greetings
type HelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message   string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updatefield_old_old_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_updatefield_old_old_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_updatefield_old_old_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_updatefield_old_old_proto protoreflect.FileDescriptor

var file_updatefield_old_old_proto_rawDesc = []byte{
	0x0a, 0x19, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2f, 0x6f, 0x6c,
	0x64, 0x2f, 0x6f, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x6e, 0x61,
	0x72, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x2f, 0x0a, 0x05, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x22, 0x44, 0x0a, 0x05, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x50,
	0x4f, 0x52, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x41, 0x53, 0x45, 0x42, 0x41, 0x4c, 0x4c, 0x10,
	0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x41, 0x53, 0x4b, 0x45,
	0x54, 0x42, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x22, 0x63, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x32, 0x47, 0x0a, 0x0c,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x08,
	0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x13, 0x2e, 0x75, 0x6e, 0x61, 0x72, 0x79,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x75, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x30, 0x34, 0x39, 0x32, 0x32, 0x31, 0x30, 0x31, 0x2f, 0x67, 0x6f,
	0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x6f, 0x6c,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_updatefield_old_old_proto_rawDescOnce sync.Once
	file_updatefield_old_old_proto_rawDescData = file_updatefield_old_old_proto_rawDesc
)

func file_updatefield_old_old_proto_rawDescGZIP() []byte {
	file_updatefield_old_old_proto_rawDescOnce.Do(func() {
		file_updatefield_old_old_proto_rawDescData = protoimpl.X.CompressGZIP(file_updatefield_old_old_proto_rawDescData)
	})
	return file_updatefield_old_old_proto_rawDescData
}

var file_updatefield_old_old_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_updatefield_old_old_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_updatefield_old_old_proto_goTypes = []interface{}{
	(HelloRequest_Sport)(0),       // 0: unary.HelloRequest.Sport
	(*HelloRequest)(nil),          // 1: unary.HelloRequest
	(*HelloResponse)(nil),         // 2: unary.HelloResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_updatefield_old_old_proto_depIdxs = []int32{
	0, // 0: unary.HelloRequest.sport:type_name -> unary.HelloRequest.Sport
	3, // 1: unary.HelloResponse.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: unary.HelloService.SayHello:input_type -> unary.HelloRequest
	2, // 3: unary.HelloService.SayHello:output_type -> unary.HelloResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_updatefield_old_old_proto_init() }
func file_updatefield_old_old_proto_init() {
	if File_updatefield_old_old_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_updatefield_old_old_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_updatefield_old_old_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_updatefield_old_old_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_updatefield_old_old_proto_goTypes,
		DependencyIndexes: file_updatefield_old_old_proto_depIdxs,
		EnumInfos:         file_updatefield_old_old_proto_enumTypes,
		MessageInfos:      file_updatefield_old_old_proto_msgTypes,
	}.Build()
	File_updatefield_old_old_proto = out.File
	file_updatefield_old_old_proto_rawDesc = nil
	file_updatefield_old_old_proto_goTypes = nil
	file_updatefield_old_old_proto_depIdxs = nil
}
